name: tests
on: [push]
jobs:
  unit-test:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
              cd ${{ github.workspace }}
              sudo apt-get install python3-venv
              python3 -m venv ./venv
              . ./venv/bin/activate
              python3 -m pip install . .[tests]
      - run: |
              cd ${{ github.workspace }}
              . ./venv/bin/activate
              python3 -m pytest ./tests/unit